---
######################################################################################
# Installs packages and configuration
# to automatically rotate your AWS key monthly
# NOTE - assumes you already have aws credentials setup manually
# NOTE - assumes you already have ansible installed, otherwise playbook wouldn't run
# NOTE - run thusly:  ansible-playbook auto_rotate_aws_keys.playbook.yml
######################################################################################

- name: Set up automatic aws key rotation
  gather_facts: True
  hosts: localhost
  connection: local
  vars:
    pip_install:
     #- awscli
      - boto
      - boto3
      - botocore
      - aws-rotate


  tasks:
  - name: Install Packages via pip
    pip:
      name: "{{ item }}"
      state: latest
      extra_args: --upgrade --user
    with_items:
      - "{{ pip_install }}"

  #NOTE  MacOS only - could be put into a block and then add other blocks for Linux/Windows
  - name: Copy launchd template to ~/Library/LaunchAgents
    template:
      src: com.tsmith.aws-rotate-keys.plist.j2
      dest: ~/Library/LaunchAgents/com.tsmith.aws-rotate-keys.plist
      mode: 0644
    when: ansible_distribution == 'MacOSX'

  - name: exec launchctl to kick it off
    shell: launchctl load com.tsmith.aws-rotate-keys.plist
    when: ansible_distribution == 'MacOSX'
